networks:
  default:
    name: pathways_network

volumes:
  pathways_db_data:


services:
  pathways_db: # refactor to pathways_db at some point
    image: pgvector/pgvector:pg18-trixie
    container_name: pathways_db
    environment:
      POSTGRES_DB: pathways
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  
    volumes:
      - pathways_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pathways"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pathways_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      PGADMIN_CONFIG_FILE_LOG_LEVEL: 10
    ports:
      - "7001:80"      
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - pathways_db
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  backend:
    image: pathways-backend:0.3.18
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: pathways_backend
    environment:
      DATABASE_URL: postgresql://admin:password@pathways_db:5432/pathways
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: pathways
      RUN_INGESTION: true
      # JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}

      PYTHONUNBUFFERED: 1

      HF_TOKEN: "" 
      HUGGING_FACE_HUB_TOKEN: ""
      
    volumes:
      - ./data:/app/data
      - ./model_cache:/root/.cache/huggingface
      - ./services/backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - pathways_db
    